#!/bin/bash

pactl load-module module-null-sink sink_name=sink_mix sink_properties=device.description="Mix microphone and speaker"
pactl load-module module-loopback source=<speaker_name>.monitor sink=sink_mix
pactl load-module module-loopback source=<mic_name> sink=sink_mix
